-- INITIALIZING STORAGE INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION external_stage_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'AZURE'
ENABLED = TRUE
AZURE_TENANT_ID = 'd1926772-dc68-4570-a90a-c504cd70b7f3' 
STORAGE_ALLOWED_LOCATIONS = ('azure://retaildatastrg.blob.core.windows.net/retaildata/');


-- TO LIST THE FILES IN EXTERNAL STAGE INTEGRATION
LIST @external_stage_integration;


-- TO DESCRIBE THE STORAGE INTEGRATION
DESC STORAGE INTEGRATION external_stage_integration;


--TENANT KEY-zwskhwsnowflakepacint_1734028108468
--TO ASSIGN NEW ROLE IN IAM OF THE ADLS TO <TENANT KEY>


-- CREAING DATABASE
CREATE DATABASE IF NOT EXISTS WAREHOUSE_DB;


--CREATING SCHEMA
CREATE SCHEMA IF NOT EXISTS BRONZE;


--USING DATABASE AND SCHEMA WHICH WE HAVE CREATED
USE DATABASE WAREHOUSE_DB;
USE SCHEMA BRONZE;


-- CREATE EXTERNAL STAGE
CREATE OR REPLACE STAGE ADLS_STAGE
URL = 'azure://retaildatastrg.blob.core.windows.net/retaildata/'
STORAGE_INTEGRATION=external_stage_integration;


--TO LIST THE FILES IN EXTERNAL STAGE
LIST @ADLS_STAGE;

LIST @ADLS_STAGE/Customers;

SHOW FILE FORMATS;

SELECT $1,$2,$3
FROM @ADLS_STAGE/Customers/customer.csv 
(FILE_FORMAT => CSV_FORMAT) 
    LIMIT 10;