--IT SHOULD BE DONE ON TABLES IN BRONZE SCHEMA OF DATABASE 

--CREATING STREAM FOR CUSTOMERS DATA TABLE
CREATE OR REPLACE STREAM CUSTOMER_DATA_STREAM ON TABLE RAW_CUSTOMER_DATA
APPEND_ONLY = TRUE;

--CREATING STREAM FOR PRODUCTS DATA TABLE
CREATE OR REPLACE STREAM PRODUCTS_DATA_STREAM ON TABLE RAW_PRODUCT_DATA
APPEND_ONLY = TRUE;

--CREATING SREAM FOR ORDERS DATA TABLE 
CREATE OR REPLACE STREAM ORDERS_DATA_SREAM ON TABLE RAW_ORDERS_DATA
APPEND_ONLY = TRUE;