--CREATING SILVER SCHEMA FOR SILVER TIER TRANSFORMATIONS
CREATE SCHEMA IF NOT EXISTS WAREHOUSE_DB.SILVER;

--USING THE SILVET SCHEMA
USE SCHEMA WAREHOUSE_DB.SILVER;

--CREATE CUSTOMER TABLE IN SILVER SCHEMA
CREATE TABLE IF NOT EXISTS SILVER.CUSTOMERS(
customer_id	INT,
name VARCHAR,
email VARCHAR,
country	STRING,
customer_type STRING,
registration_date DATE,
age INT,
gender STRING,
total_purchases INT,
updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

--CREATE PRODUCT TABLE IN SILVER SCHEMA
CREATE TABLE IF NOT EXISTS SILVER.PRODUCTS(
product_id INT,
name VARCHAR,
category STRING,
brand STRING,
price FLOAT,
stock_quantity INT,
rating FLOAT,
is_active BOOLEAN,
updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

--CREATE ORDERS TABLE IN SILVER SCHEMA
CREATE TABLE IF NOT EXISTS SILVER.ORDERS(
customer_id  INT,
payment_method STRING,
product_id INT,
quantity INT,
store_type STRING,
total_amount DOUBLE,
transaction_date DATE,
transaction_id STRING,
updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

